### ISSUE TITLE
server-side exception has occurred

### ISSUE THREAD

**Issue by adryserage** [IKatsuba/railway-template-kickback#6]
```
⨯ TypeError: Cannot read properties of null (reading 'userProfile')
    at i (.next/server/app/og/route.js:63:30)
    at async (.next/server/chunks/863.js:1:8749)
    at async K (.next/server/app/page.js:63:11338) {
  digest: '664366387'
}
```

**Comment by IKatsuba** [comment]
It looks like you do not provide RAILWAY_TOKEN or token is not valid. Just added human-readable errors for it in [this commit](https://github.com/IKatsuba/railway-template-kickback/commit/1ec6ad82f410bdcf8d571469fae65b05dd62af66)
